Add ADR for third-party security tools
18F/OPRE-Unicorn pull request #100
Opened 2021-07-20 21:07 UTC by alexsoble

## What does this change? 

Resolves #36.

## What does this change look like?

[Preview link.](https://github.com/18F/OPRE-Unicorn/blob/ars/36/adr-for-security-tools/docs/adr/009-use-github-dependabot-and-codeql.md) 👁️

2021-07-20 21:56 UTC, carjug approved these changes
lgtm!

2021-07-21 04:28 UTC, amymok requested changes
LGTM, just one change request

2021-07-21 04:28 UTC, amymok commented on docs/adr/009-use-github-dependabot-and-codeql.md
> +* GitHub offers a static analysis tool called Dependabot, which other 18F teams are using successfully.
"Dependabot" should be "CodeQL" here

2021-07-21 19:42 UTC, amymok approved these changes
LGTM!

2021-07-21 20:39 UTC, alexsoble commented
@ninamak You're the last approver on this one — I believe that once this merges, we are all done with our initial round of Architecture Decision Records / tech choices! 🎉 🎉

2021-07-21 21:38 UTC, ninamak approved these changes
LGTM!

2021-07-21 21:39 UTC, merged